language: python
python:
  - "2.7"
  - "3.6"
env:
services:
matrix:
  include:
    - python: "2.7"
      env: CONTAINER=centos:7
      services:
        - docker
      sudo: required
    
install:
  - if [[ $CONTAINER ]]; then make install-container-test CONTAINER=$CONTAINER; fi
  - if [[ ! $CONTAINER ]]; make install-test; fi
  - if [[ ! $CONTAINER ]]; && pip install .; fi

script:
  - if [[ ! $CONTAINER ]]; then make test; fi
  - if [[ $CONTAINER ]]; then make container-test; fi
