language: python
python:
  - "2.7"
  - "3.6"
env:
services:
matrix:
  include:
    - python: "2.7"
      env: CONTAINER=centos:7
      services:
        - docker
      sudo: required
    
install:
  - [[ -z $CONTAINER ]] || make install-container-test CONTAINER=$CONTAINER
  - [[ -z $CONTAINER ]] && make install-test
  - [[ -z $CONTAINER ]] && pip install .

script:
  - [[ -z $CONTAINER ]] && make test
  - [[ -z $CONTAINER ]] || make container-test
